#!/usr/bin/env bash

# Render ansible/inventory.ini from Terraform outputs.
#
# Terraform controls how many LDAP VMs exist with terraform/terraform.tfvars:
#
#   instance_count = 3
#
# This script reads the resulting ldap_backend_ips output and writes one Ansible
# host per backend. The first host is the writable provider; every later host is
# configured by Ansible as a read replica / consumer.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

terraform_dir="${TERRAFORM_DIR:-${repo_root}/terraform}"
inventory_file="${ANSIBLE_INVENTORY:-${repo_root}/ansible/inventory.ini}"
host_prefix="${OPENLDAP_HOST_PREFIX:-openldap}"
ansible_user="${ANSIBLE_USER:-ubuntu}"
ansible_key="${ANSIBLE_SSH_PRIVATE_KEY_FILE:-~/.ssh/id_rsa}"
provider_host="${LDAP_PROVIDER_HOST:-${host_prefix}-1}"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform was not found in PATH." >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 was not found in PATH." >&2
  exit 1
fi

if [ ! -d "${terraform_dir}" ]; then
  echo "Terraform directory does not exist: ${terraform_dir}" >&2
  exit 1
fi

mkdir -p "$(dirname "${inventory_file}")"

tmp_file="$(mktemp)"
terraform_output_file="$(mktemp)"
terraform_state_list_file="$(mktemp)"
trap 'rm -f "${tmp_file}" "${terraform_output_file}" "${terraform_state_list_file}"' EXIT

if ! (
  cd "${terraform_dir}"
  terraform state list -no-color > "${terraform_state_list_file}"
); then
  echo "Failed to read Terraform state from ${terraform_dir}." >&2
  echo "Run terraform apply first, then render the Ansible inventory." >&2
  exit 1
fi

if [ ! -s "${terraform_state_list_file}" ]; then
  echo "Terraform state has no managed resources in ${terraform_dir}." >&2
  echo "Run terraform apply first, then render the Ansible inventory." >&2
  exit 1
fi

if ! (
  cd "${terraform_dir}"
  terraform output -json > "${terraform_output_file}"
); then
  echo "Failed to read Terraform outputs from ${terraform_dir}." >&2
  echo "Run terraform apply first, and make sure OpenStack/Terraform credentials are available." >&2
  exit 1
fi

HOST_PREFIX="${host_prefix}" \
  ANSIBLE_USER_VALUE="${ansible_user}" \
  ANSIBLE_KEY_VALUE="${ansible_key}" \
  LDAP_PROVIDER_HOST_VALUE="${provider_host}" \
  python3 -c '
import json
import os
import sys

outputs = json.load(sys.stdin)
backend_output = outputs.get("ldap_backend_ips", {})
backend_ips = backend_output.get("value")

if not isinstance(backend_ips, list) or len(backend_ips) < 2:
    raise SystemExit("terraform output ldap_backend_ips must contain at least two backend IPs")

host_prefix = os.environ["HOST_PREFIX"]
ansible_user = os.environ["ANSIBLE_USER_VALUE"]
ansible_key = os.environ["ANSIBLE_KEY_VALUE"]
provider_host = os.environ["LDAP_PROVIDER_HOST_VALUE"]

print("# Generated by scripts/render-ansible-inventory.sh")
print("# First host is the writable provider; all later hosts are read replicas.")
print("[openldap]")
for index, ip in enumerate(backend_ips, start=1):
    print(f"{host_prefix}-{index} ansible_host={ip}")

print()
print("[openldap:vars]")
print(f"ansible_user={ansible_user}")
print(f"ansible_ssh_private_key_file={ansible_key}")
print(f"ldap_provider_host={provider_host}")
' < "${terraform_output_file}" > "${tmp_file}"

mv "${tmp_file}" "${inventory_file}"
trap - EXIT

echo "Wrote ${inventory_file}"
echo "Backends:"
sed -n '/^\[openldap\]/,/^$/p' "${inventory_file}" | sed '/^\[/d;/^$/d'
